on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        run: |
          ls -la

      - name: checagem
        run: |
          # O comando de checagem foi combinado com a referência à variável
          echo "Fazendo a checagem ${{ vars.AWS_ACCESS_KEY }}"
